import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout'
import profilePic from '../../public/images/profile/developer-pic-1.png'
import AnimatedText from '@/components/animatedtext'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout classname='pt-0'>
          <div className='flex items-center justify-between w-full '>
            <div className='w-1/2'>
              <Image src={profilePic} alt='Utkarsh' className='w-full h-auto' />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
              <AnimatedText text="From Concept  ToReality, It's All    In The Code." classname='!text-5xl !text-left' />
                <p className='my-4 text-base font-medium '>
                As a full-stack developer, I revel in the art of turning concepts into tangible digital experiences, blending front-end creativity with back-end ingenuity for seamless web applications.
                </p>
              
            </div>
          </div>
        </Layout>
      </main>
   </>  
  )
}
