import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Layout from "@/components/Layout";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/animatedtext";
import Link from "next/link";
import { LinkArrow } from "@/components/icon";
import HireMe from "@/components/HireMe";
import catface from "../../public/images/svgs/catface.svg";
import { MailIcon } from "@/components/icon";
import TransitionEffect from "@/components/TransitionEffect";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Utkarsh Rai | Portfolio </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect/>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout classname="pt-0  md:p-16 sm:p-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src={profilePic}
                alt="Utkarsh"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full ">
              <AnimatedText
                text="Crafting digital Experiences"
                classname="!text-xl !text-left font-bold break-normal xl:!text-lg lg:!text-lg md:!text-lg sm:!text-sm xs:!text-xs"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-sx">
                As a full-stack developer, I revel in the art of turning
                concepts into tangible digital experiences, blending front-end
                creativity with back-end ingenuity for seamless web
                applications.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/Resume.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light  hover:text-dark
                  border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark dark:hover:bg-dark dark:hover:text-light
                  dark:hover:border-light md:p-2 md:px-4 md:text-base"
                  download={true}
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
              </div>
              <div className="flex items-center self-start mt-2 lg:self-center ">
                <Link
                  href="mailto:raiutkarsh3219@gmail.com"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light  hover:text-dark
                  border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark dark:hover:bg-dark dark:hover:text-light
                  dark:hover:border-light md:p-2 md:px-4 md:text-base"
                  
                >
                  Contact <MailIcon className={"w-6 ml-1"}/>
                </Link>
              </div>
            </div>
          </div>
        </Layout>

        <div className="absolute right-8 bottom-8 inline-block w-24">
          <Image
            src={catface}
            alt="Utkarsh"
            className="w-full h-auto animate-bounce md:hidden"
          />
        </div>
      </main>
    </>
  );
}
